[profile.default]
solc = '0.8.21'
evm_version = 'paris'                   # Required for L2s (Optimism, Arbitrum, etc.)
src = 'contracts'
test = 'forge_tests'
out = 'out'
libs = ['lib']
match_contract = "_Local"               # Do not run fork tests
sizes = true
verbosity = 3                           # display errors
optimizer_runs = 200
block_number = 14126430
block_timestamp = 1643802347

[profile.fork] # run via FOUNDRY_PROFILE=fork foundry test
fs_permissions = [{ access = "read", path = "./deployments/mainnet" }] # Get the deployment addresses for forking
match_contract = "_Fork"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
number_underscore = "thousands"
multiline_func_header = "all"
quote_style = "double"
wrap_comments = true